# Site settings
title: Odyssey.js
description: "Built for designers, journalist and non-technical people can tell their stories"
baseurl: "/odyssey.js"
url: ""

# Build settings
markdown: kramdown
kramdown:
  use_coderay: true
permalink: pretty
encoding: utf-8
