# Site settings
title: Odyssey.js
description: "Built for designers, journalist and non-technical people can tell their stories"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
highlighter: pygments

# Assets
sass:
  sass_dir: _sass
  style: :compressed
